#!/usr/bin/env python3
"""
scripts/generate_sparc_delta_env.py
=====================================
Generate ``data/SPARC/SPARC_with_delta_real.csv`` — the per-galaxy
environmental delta table needed as the second input to
``run_h3_experiment.py``.

ΔF₃ measures the local departure of the observed gravitational acceleration
from the purely baryonic prediction.  The *global* version of this quantity
(averaged over a galaxy's full radial extent) serves as the per-galaxy
``delta_mass`` used in H3 to look for correlations with the radial-profile
autocorrelation metrics.

Concretely::

    delta_mass(galaxy) = median( ΔF₃(r) )   for all valid radial points r

A positive ``delta_mass`` means that on average the observed acceleration
exceeds the baryonic prediction (mass deficit or dark-matter dominated).

``delta_mode = 'mass'`` is the label used by ``run_h3_experiment.py`` to
select the relevant rows.

Inputs (two modes)
------------------
Mode A – from ``sparc_full_radial.csv`` (recommended):
    The radial profiles CSV already generated by
    ``generate_sparc_radial_profiles.py``.  Aggregate per galaxy.

Mode B – directly from SPARC rotation-curve files:
    Re-derive everything from scratch if the radial profiles CSV is not
    available yet.  Requires ``--sparc-dir``.

Output CSV columns
------------------
galaxy, delta_mass, delta_mode

Usage
-----
::

    # Mode A (fast – reuse radial profiles):
    python scripts/generate_sparc_delta_env.py \\
        --radial-csv data/sparc_full_radial.csv \\
        --out data/SPARC/SPARC_with_delta_real.csv

    # Mode B (standalone – derives from SPARC data directly):
    python scripts/generate_sparc_delta_env.py \\
        --sparc-dir data/SPARC \\
        --out data/SPARC/SPARC_with_delta_real.csv
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Resolve project root
# ---------------------------------------------------------------------------
_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))


# ---------------------------------------------------------------------------
# Mode A: aggregate from radial profiles CSV
# ---------------------------------------------------------------------------

def _from_radial_csv(radial_csv: Path, verbose: bool) -> pd.DataFrame:
    """Derive delta_mass by aggregating an existing sparc_full_radial.csv."""
    profiles = pd.read_csv(radial_csv)
    if 'delta_F3' not in profiles.columns:
        raise ValueError(
            f"Column 'delta_F3' not found in {radial_csv}. "
            "Run generate_sparc_radial_profiles.py first."
        )

    agg = (
        profiles
        .dropna(subset=['delta_F3'])
        .groupby('galaxy', sort=True)['delta_F3']
        .median()
        .reset_index()
        .rename(columns={'delta_F3': 'delta_mass'})
    )
    agg['delta_mode'] = 'mass'

    if verbose:
        print(f"  Leídas {len(profiles)} filas de {radial_csv}")
        print(f"  Generadas {len(agg)} galaxias con delta_mass (mediana de ΔF₃).")

    return agg


# ---------------------------------------------------------------------------
# Mode B: derive directly from SPARC rotation-curve files
# ---------------------------------------------------------------------------

def _from_sparc_dir(sparc_dir: Path, a0: float, verbose: bool) -> pd.DataFrame:
    """Derive delta_mass from raw SPARC rotmod files."""
    from src.scm_analysis import (
        load_galaxy_table,
        load_rotation_curve,
        fit_galaxy,
        _CONV,
        _MIN_RADIUS_KPC,
    )
    from src.scm_models import v_baryonic

    galaxy_table = load_galaxy_table(sparc_dir)
    galaxy_names = galaxy_table['Galaxy'].tolist()

    records = []
    n_skip = 0

    for name in galaxy_names:
        try:
            rc = load_rotation_curve(sparc_dir, name)
        except FileNotFoundError:
            if verbose:
                print(f'  [skip] {name}: rotation curve not found', file=sys.stderr)
            n_skip += 1
            continue

        fit = fit_galaxy(rc, a0=a0)
        upsilon_disk = fit['upsilon_disk']

        r_arr = rc['r'].values
        v_obs_arr = rc['v_obs'].values
        vb_arr = v_baryonic(
            r_arr,
            rc['v_gas'].values,
            rc['v_disk'].values,
            rc['v_bul'].values,
            upsilon_disk=upsilon_disk,
            upsilon_bul=0.7,
        )

        safe_r = np.maximum(r_arr, _MIN_RADIUS_KPC)
        g_bar = vb_arr ** 2 / safe_r * _CONV
        g_obs = v_obs_arr ** 2 / safe_r * _CONV
        valid = (g_bar > 0) & (g_obs > 0)

        if not np.any(valid):
            if verbose:
                print(f'  [skip] {name}: no valid radial points', file=sys.stderr)
            n_skip += 1
            continue

        delta_f3 = np.log10(g_obs[valid]) - np.log10(g_bar[valid])
        records.append({
            'galaxy': name,
            'delta_mass': float(np.median(delta_f3)),
        })

        if verbose:
            print(f'  {name}: delta_mass = {records[-1]["delta_mass"]:.4f} '
                  f'({int(valid.sum())} puntos)')

    agg = pd.DataFrame(records)
    agg['delta_mode'] = 'mass'

    print(f'\n  {len(agg)} galaxias procesadas, {n_skip} omitidas.')
    return agg


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate_delta_env(
    out_path: str | Path,
    radial_csv: str | Path | None = None,
    sparc_dir: str | Path | None = None,
    a0: float = 1.2e-10,
    verbose: bool = True,
) -> pd.DataFrame:
    """Generate ``SPARC_with_delta_real.csv``.

    Parameters
    ----------
    out_path : str or Path
        Destination CSV path.
    radial_csv : str or Path or None
        Path to an existing ``sparc_full_radial.csv`` (Mode A).
    sparc_dir : str or Path or None
        Root SPARC data directory (Mode B, used if *radial_csv* is None).
    a0 : float
        Characteristic acceleration for fitting (Mode B only).
    verbose : bool
        Print per-galaxy progress.

    Returns
    -------
    pd.DataFrame
        Generated delta table.
    """
    if radial_csv is None and sparc_dir is None:
        raise ValueError("Specify --radial-csv or --sparc-dir.")

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if radial_csv is not None:
        delta_df = _from_radial_csv(Path(radial_csv), verbose=verbose)
    else:
        delta_df = _from_sparc_dir(Path(sparc_dir), a0=a0, verbose=verbose)

    delta_df = delta_df.sort_values('galaxy').reset_index(drop=True)
    delta_df.to_csv(out_path, index=False)

    print(f'\nCSV guardado en: {out_path}')
    print(delta_df.describe())

    return delta_df


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Genera SPARC_with_delta_real.csv con delta_mass global '
                    'por galaxia (mediana de ΔF₃) para el experimento H3.',
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        '--radial-csv',
        help='Ruta a sparc_full_radial.csv ya generado (Modo A, rápido)',
    )
    group.add_argument(
        '--sparc-dir',
        help='Directorio SPARC con archivos rotmod (Modo B, independiente)',
    )
    parser.add_argument(
        '--out',
        default='data/SPARC/SPARC_with_delta_real.csv',
        help='Ruta del CSV de salida (default: data/SPARC/SPARC_with_delta_real.csv)',
    )
    parser.add_argument(
        '--a0',
        type=float,
        default=1.2e-10,
        help='Aceleración característica a₀ en m/s² (solo Modo B, default: 1.2e-10)',
    )
    parser.add_argument(
        '--quiet',
        action='store_true',
        help='Suprimir progreso por galaxia',
    )
    args = parser.parse_args()

    generate_delta_env(
        out_path=args.out,
        radial_csv=args.radial_csv,
        sparc_dir=args.sparc_dir,
        a0=args.a0,
        verbose=not args.quiet,
    )
